language: go
go:
  - 1.8
dist: trusty

before_install:
  - go get github.com/tools/godep
  - godep restore

script:
  - go build
  - docker build -t holmescode/deploy-listener:latest -t holmescode/deploy-listener:$TRAVIS_BUILD_NUMBER .
